# Generated by Django 3.0.6 on 2020-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('video', models.FileField(upload_to='classes')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default='하', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
