# Generated by Django 3.0.6 on 2020-05-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to='pracs')),
                ('score', models.IntegerField(default=0)),
                ('class_vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracs', to='classes.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
